@startuml
hide footbox

participant ":FitLogger" as FL
participant ":Storage" as ST
participant "scanner:Scanner" as SC

FL -> ST : loadData(profile)
activate ST

alt file does not exist
    ST --> FL : empty list
else file exists
    ST -> SC ** : new Scanner(file)

    ST -> ST : parseProfile(line, profile)
    activate ST
    ST --> ST
    deactivate ST

    loop for each remaining line
        ST -> SC : nextLine()
        activate SC
        SC --> ST : line
        deactivate SC
    end

    ST --> FL : workouts list
end

deactivate ST
@enduml