@startuml
hide footbox

participant ":FitLogger" as FL
participant ":Parser" as P
participant "command:ViewLastLiftCommand" as CMD
participant ":WorkoutList" as WL
participant ":Ui" as UI

-> FL : "lastlift Bench Press"
activate FL

FL -> P : parse("lastlift...", workouts, dictionary)
activate P

P -> CMD ** : new ViewLastLiftCommand("Bench Press")
P --> FL : command
deactivate P

FL -> CMD : execute(storage, workouts, ui, profile)
activate CMD

CMD -> WL : getWorkouts()
activate WL
WL --> CMD : list
deactivate WL

opt match found
    CMD -> UI : showLastLift(lift)
    activate UI
    UI --> CMD
    deactivate UI
else no match
    CMD -> UI : showMessage("No record found...")
    activate UI
    UI --> CMD
    deactivate UI
end

CMD --> FL
deactivate CMD
deactivate FL
@enduml